import {
  MODULE_ADDENDUM_MAX_BYTES_DEFAULT,
  moduleAcceptanceCommand,
  type ModuleManifest,
} from '../../config/modules.js';
import type { DraftEnvelope } from '../observability/rlm_draft.js';
import type { PromotedCorpus } from './corpus.js';

// Session 19 (design record docs/architecture/GROUNDED_AUTHORING.md §5):
// assembling the module directory from a draft plus the promoted corpus.
// The harness holds the pen: research.sourceNodeIds is pinned to the
// corpus block set (sorted, deduped — D3 flat v1), the draft contributes
// only prose (purpose, addendum, gap notes). The output is an ordinary
// module directory for human review; the driver never registers and
// never lands it (Guardrail 4).

/** New authored modules land at version 1 (a fresh, reviewed directory). */
export const AUTHORED_MODULE_VERSION = 1;

/** The addendum filename the manifest points at. */
export const AUTHORED_ADDENDUM_FILENAME = 'addendum.txt';

/**
 * Validates the draft addendum against the same rules the module loader
 * enforces (brace-freedom for rlms .format(); the size bound), BEFORE
 * anything is written. A draft that cannot land fails in the driver with
 * nothing on disk rather than producing a directory the loader rejects.
 */
export function assertAuthoredAddendum(
  text: string,
  maxBytes: number = MODULE_ADDENDUM_MAX_BYTES_DEFAULT
): void {
  if (text.trim().length === 0) {
    throw new Error('Draft addendum is empty.');
  }
  if (text.includes('{') || text.includes('}')) {
    throw new Error(
      'Draft addendum contains literal braces; rlms .format() forbids them in module addenda.'
    );
  }
  if (Buffer.byteLength(text, 'utf8') > maxBytes) {
    throw new Error(`Draft addendum exceeds its addendumMaxBytes bound (${maxBytes}).`);
  }
}

/** The addendum file body — the draft text, normalized to a trailing newline. */
export function buildAddendumText(draft: DraftEnvelope): string {
  return `${draft.addendum.replace(/\s+$/, '')}\n`;
}

export interface ManifestBuildArgs {
  moduleName: string;
  purpose: string;
  /** Pinned, sorted, deduped corpus block hashes. */
  sourceNodeIds: string[];
  addendumMaxBytes?: number;
}

/**
 * Builds the manifest object. It matches the module.json schema exactly
 * (readModuleManifest validates the written file); status is `active`
 * and kernelCompat stays 1 (no schema change this session). The pinned
 * research hashes are the ONLY provenance — the model contributed none.
 *
 * `acceptance.zeroPaid` is DERIVED from the module name, never constant:
 * a criterion every module shares discriminates nothing, which is why
 * the manifest schema now refuses a zeroPaid that does not contain the
 * manifest's own name. The name is therefore load-bearing here — there
 * is no default, because a module that cannot name its own drill has no
 * acceptance criterion and must not assemble.
 */
export function buildManifest(args: ManifestBuildArgs): ModuleManifest {
  if (args.moduleName.trim().length === 0) {
    throw new Error(
      'Cannot assemble a module with no name: acceptance.zeroPaid is derived from it.'
    );
  }
  const addendumMaxBytes = args.addendumMaxBytes ?? MODULE_ADDENDUM_MAX_BYTES_DEFAULT;
  return {
    name: args.moduleName,
    version: AUTHORED_MODULE_VERSION,
    purpose: args.purpose,
    research: { sourceNodeIds: [...args.sourceNodeIds] },
    addendum: AUTHORED_ADDENDUM_FILENAME,
    tools: [],
    bounds: { addendumMaxBytes },
    acceptance: { zeroPaid: moduleAcceptanceCommand(args.moduleName) },
    status: 'active',
    kernelCompat: 1,
  };
}

export interface ResearchDocArgs {
  moduleName: string;
  topic: string;
  corpus: PromotedCorpus;
  gapNotes: string[];
  /** How this module was produced: the paid model+date, or a replayed draft. */
  provenanceNote: string;
}

/**
 * The RESEARCH.md skeleton: names the corpus doc keys and roots, the
 * pinned block counts, the draft's gap notes, and the provenance story —
 * the human-readable record the reviewer reads before landing. Written
 * in the module #1 RESEARCH.md mold, but generated by the harness so the
 * derivation story is never something the model narrated about itself.
 */
export function buildResearchDoc(args: ResearchDocArgs): string {
  const totalBlocks = new Set(args.corpus.blocks.map(b => b.hash)).size;
  const lines: string[] = [];
  lines.push(`# ${args.moduleName} — research provenance`, '');
  lines.push(
    'This module was authored under the grounded-authoring mode (design record',
    '`docs/architecture/GROUNDED_AUTHORING.md`): the promoted research corpus below was',
    'seeded block-aligned into a read-only-scope workspace, the draft was produced with',
    'no database or search access, and `research.sourceNodeIds` in `module.json` was',
    'pinned by the harness from the corpus — not chosen by the model (§5).',
    ''
  );
  lines.push(`**Topic:** ${args.topic}`, '');
  lines.push('## Research corpus', '');
  lines.push('| Promoted doc key | Version | Root hash | Blocks |', '|---|---|---|---|');
  for (const doc of args.corpus.documents) {
    lines.push(
      `| \`${doc.docKey}\` | ${doc.version} | \`${doc.rootHash}\` | ${doc.blockHashes.length} |`
    );
  }
  lines.push('', `Total pinned research blocks (deduped): ${totalBlocks}.`, '');
  lines.push(
    'Because these doc keys are stable, re-promoting changed corpus content versions the',
    'same document and the invalidation sweep contests this module\'s graph entity',
    `(\`module:${args.moduleName}\`) once it is registered (design record §9.4). Recover it`,
    'by re-reviewing the protocol against the refreshed research and re-registering.',
    ''
  );
  lines.push('## Authoring provenance', '');
  lines.push(args.provenanceNote, '');
  lines.push('## Declared gaps', '');
  if (args.gapNotes.length === 0) {
    lines.push('The draft declared no gaps: the corpus covered everything the protocol required.', '');
  } else {
    lines.push('The draft declared these gaps — topics the corpus did not cover:', '');
    for (const note of args.gapNotes) {
      lines.push(`- ${note}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}
